language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=1.8.17
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.5

install: 
  - pip install -q Django==$DJANGO_VERSION

script:
  - python setup.py install
  - python runtests.py
