# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hourlyCost', models.FloatField(default=0.0)),
                ('category_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labAdmin.Category_Device')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('admin', models.BooleanField(default=False)),
                ('sync', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourlyCost', models.FloatField(default=0.0)),
                ('bootDevice', models.DateTimeField()),
                ('startWork', models.DateTimeField()),
                ('finishWork', models.DateTimeField()),
                ('shutdownDevice', models.DateTimeField()),
                ('inWorking', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labAdmin.Device')),
            ],
        ),
        migrations.CreateModel(
            name='LogError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('nfc', models.IntegerField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hour_start', models.TimeField()),
                ('hour_end', models.TimeField()),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('role_kind', models.IntegerField(choices=[(0, 'Door Access'), (1, 'Use Device')])),
                ('valid', models.BooleanField(default=True)),
                ('category_devices', models.ManyToManyField(blank=True, to='labAdmin.Category_Device')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('firstSignup', models.DateField()),
                ('lastSignup', models.DateField()),
                ('endSubcription', models.DateField()),
                ('needSubcription', models.BooleanField(default=True)),
                ('nfcId', models.IntegerField(null=True, unique=True)),
                ('groups', models.ManyToManyField(to='labAdmin.Group')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labAdmin.User'),
        ),
        migrations.AddField(
            model_name='logdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labAdmin.User'),
        ),
        migrations.AddField(
            model_name='logaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labAdmin.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='roles',
            field=models.ManyToManyField(to='labAdmin.Role'),
        ),
    ]
