# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='group',
            name='sync',
        ),
    ]
