# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hourlyCost',
            field=models.FloatField(default=0.0),
        ),
    ]
