# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labAdmin', '0002_device_hourlycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='labAdmin.User'),
            preserve_default=False,
        ),
    ]
