# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 17:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labAdmin', '0004_permission_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdoor',
            name='hour',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 5, 17, 20, 4, 842118)),
        ),
    ]
